sudo: required

language: ruby

before_script:
  - sudo wget -O /usr/local/bin/yaml https://github.com/mikefarah/yaml/releases/download/1.11/yaml_linux_amd64
  - sudo chmod a+x /usr/local/bin/yaml

script:
  - /usr/bin/find . -name *.yml -type f -exec /usr/local/bin/yaml r {} \;